### ISSUE TITLE
Incorrect address checked in function `get_miner_data`

### ISSUE THREAD

**Issue by giuliop** [grzracz/OrangeCLI#7]
Commit c4315ca44574d2545b98ec2a739585544affc96a added a new function `get_miner_data`.

The function tries to fetch the `apps-local-state` info for the miner account to check the current effort.
Since the miner account is not opted-in the application, it fails, making running the script fail with this error:

File "main.py", line 119, in get_miner_data
    local_state = next(iter([app["key-value"] for app in account_info["apps-local-state"] if app_id == str(app["id"])]))
StopIteration

The function should instead check the deposit address for that information.
I will submit a PR with the simple fix.

**Comment by grzracz** [comment]
Fixed

**Comment by busayo59** [comment]
Amazing
